apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: collector-staging-tls
spec:
  secretName: collector-staging-tls
  dnsNames:
    - staging.chaker.pro
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
