FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o auth-service .

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /app/auth-service /app/auth-service

EXPOSE 8080

CMD ["/app/auth-service"]
